#ifndef H5D31D8DF_B49E_41F5_A9FC_D9FD53F01E1E
#define H5D31D8DF_B49E_41F5_A9FC_D9FD53F01E1E

#include "mcl/keyword.h"
#include "mcl/container_of.h"

MCL_STDC_BEGIN

#define MCL_INTF_OPS_TYPE(TYPE)   TYPE##Ops
#define MCL_INTF_OPS_INST(TYPE)   TYPE##_ops

#define MCL_INTF_DEF(TYPE)								\
typedef struct MCL_INTF_OPS_TYPE(TYPE) MCL_INTF_OPS_TYPE(TYPE);	\
typedef struct TYPE TYPE;								\
struct TYPE {											\
	MCL_INTF_OPS_TYPE(TYPE) *ops;						\
};														\
struct MCL_INTF_OPS_TYPE(TYPE)

#define MCL_INTF_DEF_OPS(TYPE)							\
MCL_PRIVATE MCL_INTF_OPS_TYPE(TYPE) MCL_INTF_OPS_INST(TYPE) =

#define MCL_INTF(TYPE)	__##TYPE

#define MCL_INTF_IMPL(TYPE)	 TYPE MCL_INTF(TYPE)
#define MCL_DEPS_INTF(TYPE)  TYPE* MCL_INTF(TYPE)

#define MCL_INTF_CAST_TO(INTF_TYPE, INTF_PTR, TYPE, TYPE_PTR)\
TYPE* TYPE_PTR = MCL_CONTAINER_OF(INTF_PTR, TYPE, MCL_INTF(INTF_TYPE))

#define MCL_INTF_OF(TYPE_PTR, INTF_TYPE) (TYPE_PTR->MCL_INTF(INTF_TYPE))
#define MCL_INTF_SELF(INTF_TYPE) MCL_INTF_OF(self, INTF_TYPE)
#define MCL_INTF_SELF_P(INTF_TYPE) (&MCL_INTF_OF(self, INTF_TYPE))

#define MCL_INTF_INIT_OPS(INTF_PTR, INTF_TYPE) INTF_PTR->ops = &MCL_INTF_OPS_INST(INTF_TYPE)
#define MCL_INTF_IMPL_OPS(TYPE_PTR, INTF_TYPE) MCL_INTF_INIT_OPS((&MCL_INTF_OF(TYPE_PTR, INTF_TYPE)), INTF_TYPE)

#define MCL_INTF_INIT_SELF_OPS(INTF_TYPE) MCL_INTF_INIT_OPS(self, INTF_TYPE)
#define MCL_INTF_IMPL_SELF_OPS(INTF_TYPE) MCL_INTF_INIT_OPS(MCL_INTF_SELF_P(INTF_TYPE), INTF_TYPE)

#define MCL_INTF_DEPS_OF(TYPE_PTR, DEPS_TYPE) (TYPE_PTR->MCL_INTF(DEPS_TYPE))
#define MCL_INTF_SELF_DEPS(DEPS_TYPE) MCL_INTF_DEPS_OF(self, DEPS_TYPE)

MCL_STDC_END

#endif
